### ISSUE TITLE
Release

### ISSUE THREAD

**Issue by ChrisMcKee** [terraform-providers/terraform-provider-ns1#13]
@alistanis Hi; I've built this manually for now as I needed the meta attributes; is there a public roadmap for this stuff / hashicorp stuff in general, around release dates for builds (seeing there are no nightlies)? 

Thanks for the effort pulling all the outstanding PRs in and the extra clean-ups, it's greatly appreciated.

**Comment by alistanis** [comment]
@ChrisMcKee Sorry I haven't gotten back to you yet, things have been a little busy since the start of the new year and this notification slipped through my email! Thanks for the kind words, I appreciate that.

It's my understanding that Hashicorp pulls in the master branches of the Terrraform providers when they push a new release of Terraform - the most recent PR was my first major one to a provider repository and I've only built it locally as well, so I'll check on that to confirm for you. @pashap do you know if this is correct?

As for us at NS1, we don't currently have a public roadmap for this, but if it's something you think could be beneficial, I'll talk it over with @markmpeterson and see what we can do. In the meantime, tomorrow I'm going to update/close the issues that were addressed in the release I pushed recently.

**Comment by ChrisMcKee** [comment]
@alistanis totally thought you were part of Hashi 😁 
I built out our many domains / bulky dns layout using a compiled version of master (manually bunging it in the plugin folder) setting the weights in the meta and the filters and all that stuff seems fine. 
CAA is probably the only thing I'm still waiting on from the list, but as it stands masters looking pretty good.
Thanks for the update 👍

**Comment by alistanis** [comment]
@ChrisMcKee Haha I'll take that as a compliment! I'll see what I can do about CAA, it might only be a small change here or in our Golang SDK. I'll post an update after I spend a little time investigating it.

Thanks!

**Comment by ChrisMcKee** [comment]
@alistanis firstly, yey release came out. 
Other than that the only issues I have are caused by the API rather than the terraform provider.
I'm splitting between NS1 + R53 for DR (ideally it would of been Active / Passive but most registras lack an api so we're active/active); the API creates the NS record on zone create so I have to do a little dance for each new domain.

For the AWS portion I use

```
resource "aws_route53_record" "r53_ns" {
  zone_id = "${aws_route53_zone.r53_rootzone.zone_id}"
  name    = ""
  type    = "NS"
  ttl     = "8400"
  records = ["${slice(split(",", ns1_zone.ns1_rootzone.dns_servers),0,2)}", "${slice(aws_route53_zone.r53_rootzone.name_servers,0,2)}"]
}
```

I then leave the NSone equivalent out while the domains created;
Login to the NSone portal; delete the NS record.
Go back and manually populate the answers for NS in the NS one portion (the answers object is awkward for automation) ala

```
resource "ns1_record" "ns1_ns1" {
  zone = "${ns1_zone.ns1_rootzone.zone}"
  domain = "${var.domain_name}"
  type    = "NS"
  ttl     = "8400"

  answers = { answer = "dns1.pxx.nsone.net" }
  answers = { answer = "dns2.pxx.nsone.net" }
  answers = { answer = "ns-xx.awsdns-29.co.uk" }
  answers = { answer = "ns-xx.awsdns-58.com" }

}
```

The answers struct is weird to deal with (as well as grammatically incorrect, my answers can contain a multiple answer and meta lol).
The downside is for simple data (ala ns records) I can't just shove an array in.

Not the end of the world just creates a weird requirement for me to do manual leg once per domain.

**Comment by ChrisMcKee** [comment]
@alistanis I believe you have to tag for a release; terraforms still pulling 0.1.0

**Comment by poblahblahblah** [comment]
Would love to see a release tagged and cut for this. I've been testing out a compiled version of master and everything we've done looks good so far.

**Comment by alistanis** [comment]
@ChrisMcKee thanks for the update Chris, I didn't know I needed to tag for it. I'll figure out how to do that and make sure it gets in the next one. @poblahblahblah , @ChrisMcKee  Sorry for the inconvenience there. 

I know the docs on the Terraform site aren't updated yet, but you should be able to use answers as an array now - I changed that behavior when I modified the provider. It would look like:

`resource "ns1_record" "ns1_ns1" {
  zone = "${ns1_zone.ns1_rootzone.zone}"
  domain = "${var.domain_name}"
  type    = "NS"
  ttl     = "8400"

  answers = [ {answer = "dns1.pxx.nsone.net" }, {answer = "dns2.pxx.nsone.net", meta = {...} }, ... ]
}`

That being said, meta complicates this a bit and you wouldn't be able to use the split() method like you're doing with aws since it's a much more complicated beast. Would that help your process for simpler answers? If not, we should chat about possible ways we can improve it.

**Comment by ChrisMcKee** [comment]
Thanks. It's as simple as creating a tag v0.1.1 github creates a release.
Hashicorps docs are a tad crap around the plugin system/releases.

I think with the NS record, the question would be, why would you use meta on those records? Is there even a use case for that?

Still with the NS record the chicken and the egg issue with the API auto creating the NS record outside of the state change being made will still break any attempt to set the NS record without first manually removing it.
