### ISSUE TITLE
Updating a user isn't applying the permissions

### ISSUE THREAD

**Issue by poblahblahblah** [terraform-providers/terraform-provider-ns1#15]
### Terraform Version
```
Terraform v0.11.1
+ provider.ns1 <master>
```

### Affected Resource(s)
- ns1_user

### Terraform Configuration Files
```hcl
resource "ns1_user" "Human_User" {
  name     = "Human User"
  username = "human_user"
  email    = "human.user@example.com"

  teams = ["${ns1_team.devops_users.id}"]

  notify {
    billing = true
  }
}
```

### Debug Output
First terraform apply: https://gist.github.com/poblahblahblah/db9e304f6b17406fb4fde398b7efa57c
Second terraform apply: https://gist.github.com/poblahblahblah/a767b44722d71df65443d5959e739096

### Panic Output
N/A

### Expected Behavior
There should have been no permissions change to the user

### Actual Behavior
The users permissions never get updated, so terraform plan/apply always thinks there are changes to be made.

### Steps to Reproduce
1. create a user with the above HCL snippet
2. `terraform apply`
3. `terraform apply`

### Important Factoids
None

### References
None

**Comment by mburtless** [comment]
Think I've uncovered what's actually going on here.  The issue is related permissions inheritance from a team.

Essentially, when you add a user to a team (as in config above), the user inherits permissions from the team.  Since this updates the user's permissions to something other than what Terraform thinks is specified in the config, it detects a change is required the next time `plan` or `apply` is run.

On `apply` Terraform will submit the changes it thinks are required to bring the user back to the permissions indicated in the config (without the inherited permissions) to the NS1 API.  NS1 accepts these changes and responds with HTTP/200, but effectively ignores them due to the inheritance from the team membership.

The fix here is likely to update ns1_user to ignore permissions changes when team membership is detected.
