### ISSUE TITLE
Unable to create notify list

### ISSUE THREAD

**Issue by davidmarkstartapp** [terraform-providers/terraform-provider-ns1#34]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_notifylist

### Terraform Configuration Files
```hcl
resource "ns1_notifylist" "general" {
  name = "ns1-general-notifications"

  notifications = {
    type = "slack"

    config = {
      username = "ns1-bot"
      url          = "https://hooks.slack.com/services/xxx"
      channel  = "ns1-notifications"
    }
  }

  notifications = {
    type = "datafeed"

    config = {
      sourceid = "${ns1_datasource.nsone_monitoring.id}"
    }
  }
}
```

### Expected Behavior
Create new notify list with Slack and data feed to managed dns metadata records

### Actual Behavior
`ns1_notifylist.general: PUT https://api.nsone.net/v1/lists: 500 Internal server error`

**Comment by mburtless** [comment]
The issue here is likely with the `slack` notification, not the `datafeed` one.

Underlying problem is that `resourceDataToNotifyList()` only translates `webhook` `email` and `datafeed` types of notifications to their appropriate creation methods in the NS1 SDK.  The SDK itself has support for the rest of the types that NS1 supports, so resolving this should be fairly easy.  The method itself should also be updated to throw an error if an unsupported notification type is provided.
