### ISSUE TITLE
Add the ability to configure feeds for records up filter

### ISSUE THREAD

**Issue by davidmarkstartapp** [terraform-providers/terraform-provider-ns1#35]
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
- ns1_record
- ns1_datafeed

### Terraform Configuration Files
```hcl
resource "ns1_datafeed" "api" {
  name      = "${ns1_record.primary_api.domain}"
  source_id = "${module.notification_list.datasource_ns1_monitoring}"

  config = {
    jobid = "${ns1_monitoringjob.api.id}"
  }
}

resource "ns1_record" "api" {
  zone   = "${ns1_zone.example_com.zone}"
  domain = "api.${ns1_zone.example_com.zone}"
  type   = "CNAME"
  ttl    = 900

  answers = [
    {
      answer = "${ns1_record.primary_api.domain}"

      meta = {
        priority = 0
        up       = true
      }
    },
    {
      answer = "${ns1_record.secondary_api.domain}"

      meta = {
        priority = 1
        up       = true
      }
    },
  ]

  filters = {
    filter = "up"
  }

  filters = {
    filter = "priority"
  }
}
```

### Expected Behavior
This configuration works find but I'd like to be able configure it as the following
```hcl
  answers = [
    {
      answer = "${ns1_record.primary_api.domain}"

     feeds = [
                {
                    feed = "${ns1_datafeed.api.id}"
                    source = "${module.notification_list.datasource_ns1_monitoring}"
                }
            ],

      meta = {
        priority = 0
        up       = {
          feed = "${ns1_datafeed.api.id}"
         }
      }
    },
    {
      answer = "${ns1_record.secondary_api.domain}"

      meta = {
        priority = 1
        up       = true
      }
    },
  ]
```

### Actual Behavior
Maybe there is another option to get this. I'd like to hear that

### References
When adding the feeds manually from NS1 portal, im getting the same crash as GH-31 mentioned

Thanks

**Comment by glennslaven** [comment]
Any update on this?

**Comment by glennslaven** [comment]
So digging  into the code, the issue isn't so much in the terraform provider as in the NS1 Go client.  
In the `MetaFromMap` function it's checking the value of the `up` meta value and if it's not `1` if sets it to false.  https://github.com/ns1/ns1-go/blob/v2/rest/model/data/meta.go#L243

I had tried doing this:

```
     meta = {
        up   = "{ feed: \"245g35g3523g235b95cfd\" }"
      }
```

But the call made to the API is always rewritten to `up: false`

**Comment by alistanis** [comment]
@glennslaven Thanks for taking the time to deal with that. The reason we chose not to address these types of issues is indeed because of Terraform 0.12.0. We had work underway to fix the majority of issues with the current provider, but I stopped working on it once I saw the announcements for 0.12.0, which will obsolete any workarounds I was going to introduce and make managing nested and dynamic types much, much easier. I've spoken with Hashi about their timeline, and they still haven't given us anything concrete other than end of summer at best, or pushed into next year at absolute worst, but we're cautiously optimistic at NS1. As soon as they have an alpha/beta/RC, I'll begin working on the provider again to get it in line so that it'll be ready when 0.12.0 is released. Thanks for your patience,

Chris

**Comment by davidmarkstartapp** [comment]
Thank you both!
We already started to use this plugin but decided that for the smart records we will maintain manually :(
Hope to manage the entire ns1 account with this plugin 👍

**Comment by dopry** [comment]
@alistanis 0,12 is on the horizon, but I think the adoption curve will be slow. I know I'm not going to rush out and update my client's terraform configuration to work with 0.12 on release date. It'll take us a couple years to move all of our legacy clients. Not having this feature will block people with legacy terraform infrastructure from migration NS to NS1.
