### ISSUE TITLE
Simpler answer format

### ISSUE THREAD

**Issue by pgray** [terraform-providers/terraform-provider-ns1#52]
Hey there,
I think it'd be a much simpler format for tf files if you didn't need multiple `answers` sections.

Instead of:
```
answers {
  answer = "asdf.com"
}
answers {
  answer = "jkl.com"
}
```

I think:
```
answers [ "asdf.com", "jkl.com" ]
```
or:
```
answers {
  answer = "asdf.com"
  answer = "jkl.com"
}
```
would be a bit saner.
If this is trivial, I'd be happy to help contribute.
Also maybe there are some edge-cases that this format doesn't handle well.

**Comment by mburtless** [comment]
After working on the provider a bit, I'm seeing why this is the current state: this is a 1:1 map to the representation of records in NS1's API.

As in the API, each Answers entry is a dictionary and not just a string, because they can optionally be associated with things like `region` and `meta`. i.e:
```
answers {
    answer = "a.example.com."
    region = "ExampleRegionA"

    meta = {
      up          = true
    }
  }

answers {
    answer = "b.example.com."
    region = "ExampleRegionB"
}
```
Behind the scenes, Terraform turns the above into a list of dictionaries, which is how it's represented in the API as well. So the other way this could be written is:
```
  answers = [
     {
       answer = "a.example.com."
       region = "ExampleRegionA"

       meta = {
         up          = true
         connections = 4
         latitude    = 0.5
        georegion   = "US-EAST"
       }
     },
     {
       answer = "b.example.com."
       region = "ExampleRegionB"
     },
   ]
```
Which looks a little more sane.  I still wonder if there isn't a better abstraction we could be using here to make this easier.  Maybe turn answer into a separate resource which people can then provide to a record resource?
```
resource "ns1_answer" "my_answer1" {
   answer = "a.example.com."
   region = "ExampleRegionA"
}

resource "ns1_answer" "my_answer2" {
   answer = "b.example.com."
   region = "ExampleRegionB"
}

resource "ns1_record" "my_record" {
   zone = "my-zone.com"
   domain = "my-record.my-zone.com"
   type = "CNAME"
   ttl = 10800
   answers = ["${ns1_answer.my_answer1}, ${ns1_answer.my_answer2}"]
}
```

**Comment by pgray** [comment]
Oh I really like the separated out answer resource idea.
That seems more idiomatic, but that could also just be my opinion.

**Comment by sc0ttbeardsley** [comment]
This can be closed, ya?

**Comment by rupa** [comment]
yeah, lets close it. We'll keep the discussion and ideas in mind.

**Comment by etsuo** [comment]
As you guys ponder this... for anyone trying to dynamically generate multiple answers for an A record, here's an example of how you can use dynamic nested blocks in Terraform 0.12.

```
variable "somewhere-com-a-records" {
  default = {
    "a-sample-a-record"        : ["1.2.3.4", "1.2.3.5"]
    "b-sample-a-record"        : ["1.2.3.3"]
  }
}

resource "ns1_zone" "somewhere-com" {
  zone = "somewhere.com"
}

resource "ns1_record" "somewhere-com-A" {
  for_each = var.somewhere-com-a-records
  zone    = ns1_zone.somewhere-com.zone

  type    = "A"
  ttl     = 300
  domain  = "${each.key}.${ns1_zone.somewhere-com.zone}"

  # dynamic nested block magic (see: 
  dynamic "answers" {
    for_each = each.value
    content {
      answer = answers.value
    }
  }
}
```
