### ISSUE TITLE
Add support to enable DNSSEC

### ISSUE THREAD

**Issue by doradojl** [terraform-providers/terraform-provider-ns1#63]
Hi there,

NS1 supports DNSSEC, but the terraform provider doesn't have an option when a zone is created to enable it.

https://ns1.com/api#post-enable-dnssec-for-a-zone

**Comment by mburtless** [comment]
Hi @doradojl, thanks for reporting this.

The underlying issue here is NS1's [Go SDK](https://github.com/ns1/ns1-go) does not support configuring DNSSEC on Zones.  Until support is added there, it can not be added to this provider.

I've created a new issue for this in the [SDK](https://github.com/ns1/ns1-go/issues/66)

**Comment by doradojl** [comment]
Thanks for the answer!

**Comment by doradojl** [comment]
Please correct me if I'm wrong. 

The ns1-go library has the function zones.updates. This is the function we need to enable/disable the DNSSEC based on the API doc.

https://ns1.com/api#post-enable-dnssec-for-a-zone

But I guess that option only appears if NS1 allows you yo use DNSSEC in your account.

**Comment by mburtless** [comment]
Yes, the library supports updating attributes of zones, but there's further enhancement necessary to support updating the `dnssec` attribute, as the library's Zone model doesn't include the dnssec attribute.

Contributions are welcome, so feel free to open a PR if against that repo if you'd like to take a crack at that!

**Comment by mburtless** [comment]
Closing this out as support for toggling `dnssec` attribute on a zone and a new `dnssec` data source has been added in v1.5.3 of the provider.
